export const Skills=[
    {
        name:"Bootstrap",
        src:"bootstrap.png",
        alt:"bootstrap"
    },
    {
        name:"CSS",
        src:"css.jpg",
        alt:"css"
    },
    {
        name:"GraphQL",
        src:"graphql.png",
        alt:"graphql"
    },
    {
        name:"HTML",
        src:"html.jpg",
        alt:"html"
    },
    {
        name:"JavaScript",
        src:"javascript.png",
        alt:"javascript"
    },
    {
        name:"MongoDB",
        src:"mongoDB.jpg",
        alt:"mongoDB"
    },
    {
        name:"Node",
        src:"node.png",
        alt:"node"
    },
    {
        name:"React",
        src:"react.png",
        alt:"react"
    },
    {
        name:"SQL",
        src:"sql.png",
        alt:"sql"
    },
    {
        name:"TypeScript",
        src:"typescript.png",
        alt:"typescript"
    },
    {
        name:"Vue",
        src:"vue.jpeg",
        alt:"vue"
    },
    {
        name:"Webpack",
        src:"webpack.png",
        alt:"webpack"
    },
    {
        name:"Angular",
        src:"angular.png",
        alt:"angular"
    },
    {
        name:"Git",
        src:"git.jpg",
        alt:"git"
    },
    {
        name:"Heroku",
        src:"heroku.jpeg",
        alt:"heroku"
    },
    {
        name:"Postman",
        src:"postman.png",
        alt:"postman"
    },
    {
        name:"Bulma",
        src:"bulma.png",
        alt:"bulma"
    }
];
